version: "3.9"
services:
  # main proxy server that keeps a session
  proxy:
    build: proxy
    volumes:
      - shared:/shared
      - ./pki:/etc/nginx/pki:ro
    environment:
      - COOKIE_PATH=/shared/cookies.conf
      - SOCK_PATH=/shared/sock
    ports:
      - 1000-2000:80
      - 1000-2000:443

  # agent to login and obtain a session
  login:
    build: ./ntu
    secrets:
      - credentials.json
    volumes:
      - shared:/shared
    environment:
      - CRED_PATH=/run/secrets/credentials.json
      - COOKIE_PATH=/shared/cookies.conf
      - SOCK_PATH=/shared/sock

secrets:
  credentials.json:
    file: .credentials.json

volumes:
  shared:
