version: "3.9"
services:
  # main proxy server that keeps a session
  proxy:
    build: proxy
    volumes:
      - shared:/shared:ro
      # TODO: fix uid mismatch with outside
      - ./pki:/etc/nginx/pki:ro
    environment:
      - COOKIE_PATH=/shared/cookies.conf
    ports:
      - 1000-2000:80
      - 1000-2000:443

  # agent to login and obtain a session
  login:
    build: ./ntu
    secrets:
      - credentials.json
    volumes:
      - shared:/shared
    environment:
      - CRED_PATH=/run/secrets/credentials.json
      - COOKIE_PATH=/shared/cookies.conf
      # for nginx to access shared cookies file
      - UID=101
      - GID=101

secrets:
  credentials.json:
    file: .credentials.json

volumes:
  shared:
