#!/bin/sh

set -eux

# On the router whose LAN is included in the VPN,
# packets from the LAN need no NAT masquerade,
# so remove those rules to allow the VPN host to identify
# which client in the LAN is accessing

sudo=$(command -v sudo)

add_rule() {
    if ! $sudo iptables -t nat -C "$@" >/dev/null 2>&1; then
        $sudo iptables -t nat -A "$@"
    fi
}

del_rule() {
    $sudo iptables -t nat -D "$@"
}

show_rules() {
    $sudo iptables-save -t nat
}


tundev=$(cat /proc/$(pidof openvpn)/fdinfo/* | grep -Eo 'tun[0-9]+')
tunip=$(ip address show dev $tundev |
    sed -En 's/^.*inet ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).*$/\1/p' | head -n1)

del_rule POSTROUTING ! -s $tunip/32 -o tun15 -j MASQUERADE

show_rules

